# Generated by Django 2.2.4 on 2019-09-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190925_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_created_by',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('coordinatedBy', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='event',
            new_name='event_participants',
        ),
    ]
