# Generated by Django 2.2.4 on 2019-09-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_participants_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='userName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='event_created_by',
            name='coordinatedBy',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='event_created_by',
            name='eventName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='userName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
