# Generated by Django 2.2.4 on 2019-09-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190929_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_created_by',
            name='coordinatedBy',
            field=models.CharField(max_length=100),
        ),
    ]
