# Generated by Django 2.2.4 on 2019-09-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190929_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_created_by',
            name='eventName',
            field=models.CharField(max_length=100),
        ),
    ]
